### ISSUE TITLE
Error command output

### ISSUE THREAD

**Issue by StrawberryNature** [Matze997/NickUI#1]
Hello my mother tongue is actually German but I still write this issue in English. I think this plugin has a potential, only I got an error message and can not use it. When starting from the server, it also does not create a config file.
error message:
[Server thread/CRITICAL]: Error: "Class 'jojoe77777\FormAPI\SimpleForm' not found" (EXCEPTION) in "plugins/NickUI_dev-1.phar/src/matze/nickui" at line 31

**Comment by Matze997** [comment]
Hey StrawberryNature,
Yeah it was my mistake because i had forgotten to siad that FormAPI is have to be installed. I will add FormAPI. Thanks for the Issue. The Config will be shown when you opend the UI the first time. I know this bug i don´t kno how to fix this.

**Comment by StrawberryNature** [comment]
I like to help them therefore a new incentive;) I have discovered if I now open the user interface, and want to have a custom nick is the title $ lCustom Nick (is probably accidentally happened), should now still be a § right? are only small things.

**Comment by Matze997** [comment]
Ups, yeah. xD
I will look in the futere if there are any spell mistakes. There were a lot
at tge beginning. :-D

StrawberryNature <notifications@github.com> schrieb am Fr., 6. Sep. 2019,
14:06:

**Comment by StrawberryNature** [comment]
ok is changeable in the config itself. cool that I can thank you.

**Comment by StrawberryNature** [comment]
the last thing I found:
If I change my mind and press the X to close the user interface I get this,

[Server thread/CRITICAL]: TypeError: "Argument 2 passed to matze\nickui::matze\{closure}() must be of the type array, null given, called in phar://C:/Users/hombe/Documents/PMMP/plugins/FormAPI.phar/src/jojoe77777/FormAPI/Form.php on line 46" (EXCEPTION) in "plugins/NickUI_dev-4.phar/src/matze/nickui" at line 73

**Comment by Matze997** [comment]
Ohhh, big thank you for searching all this mistakes. The Not-Allowed-Name
feature is done but now i have to fix this error😁. I hope i will get it.
And again big thank you👍👍👌

StrawberryNature <notifications@github.com> schrieb am Fr., 6. Sep. 2019,
14:40:

**Comment by StrawberryNature** [comment]
haha do not thank me but the people on my server ^^

**Comment by Matze997** [comment]
What's your Server IP? I will thank them all😁👍 And btw the Plugin is
done. Puhhhh that were really hard. xD

StrawberryNature <notifications@github.com> schrieb am Fr., 6. Sep. 2019,
14:54:

**Comment by StrawberryNature** [comment]
unfortunately still with the X in the menu of custom nick

[Server thread/CRITICAL]: TypeError: "Argument 2 passed to matze\nickui::matze\{closure}() must be of the type array, null given, called in phar://C:/Users/hombe/Documents/PMMP/plugins/FormAPI.phar/src/jojoe77777/FormAPI/Form.php on line 46" (EXCEPTION) in "plugins/NickUI_dev-5.phar/src/matze/nickui" at line 73

also this function does not work
not-allow-custom-nicks:
since I can name myself as ServerTeam without op and with the guest group of pureperms with the permission "nick.use"
