### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by StrawberryNature** [Matze997/NickUI#2]
could you possibly insert a function into the configuration file that will not allow certain nicks to be used? (eg the sever team) would be good that you can not handle this with custom nick

**Comment by Matze997** [comment]
Ok, i will add this

StrawberryNature <notifications@github.com> schrieb am Fr., 6. Sep. 2019,
14:21:

**Comment by StrawberryNature** [comment]
Thank you, I do not want to rush but I'm just thrilled

**Comment by StrawberryNature** [comment]
oops should have added here ... sry
the function is not correct, because I can call myself a ServerTeam without op and with the guest group of pureperms with the permission nick.use

**Comment by StrawberryNature** [comment]
synonymous, I always have to remove the folder in plugindata so that the new config file is displayed ...

**Comment by Matze997** [comment]
Against that i only can do a Config Updater but it´s seamless because the Plugin won´t get so much updates any more

**Comment by StrawberryNature** [comment]
exactly, because now everything works.

**Comment by StrawberryNature** [comment]
except maybe the text between the input field and the title of the custom nick, can not be colorized or removed XD

**Comment by Matze997** [comment]
Yeah, should i add it?

StrawberryNature <notifications@github.com> schrieb am Fr., 6. Sep. 2019,
15:57:

**Comment by StrawberryNature** [comment]
is just my taste without text, others may want to keep it. if you can do that, like :)

**Comment by Matze997** [comment]
Removing the text isn't possible i think. The Client will Crash

StrawberryNature <notifications@github.com> schrieb am Fr., 6. Sep. 2019,
16:15:

**Comment by StrawberryNature** [comment]
If that is the case, we will probably let the text pass better.
